# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-02 10:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('madeasy_auth', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_initial',
        ),
    ]
