# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-21 21:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingstatus',
            name='name',
            field=models.CharField(choices=[('CONFIRMED', 'CONFIRMED'), ('PENDING', 'PENDING')], max_length=50),
        ),
    ]
