# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-01 19:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_flightdetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingstatus',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='bookingstatus',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='flightdetails',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='flightdetails',
            name='passenger',
        ),
        migrations.RemoveField(
            model_name='flightdetails',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='tickettype',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='tickettype',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='ticket_type',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='travel_class',
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_status',
            field=models.CharField(choices=[('CONFIRMED', 'CONFIRMED'), ('PENDING', 'PENDING')], default='PENDING', max_length=50),
        ),
        migrations.DeleteModel(
            name='BookingStatus',
        ),
        migrations.DeleteModel(
            name='FlightDetails',
        ),
        migrations.DeleteModel(
            name='TicketType',
        ),
    ]
