# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-18 13:07
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airline', '0002_auto_20160315_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='equipment',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(help_text='3-letter codes for plane type', max_length=3), size=None),
        ),
    ]
