# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-01 19:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_auto_20160501_2202'),
        ('airline', '0004_citylookup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='airplane',
            name='airline',
        ),
        migrations.RemoveField(
            model_name='airplane',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='airplane',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='travelclass',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='travelclass',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='travelclassseatcapacity',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='travelclassseatcapacity',
            name='flight',
        ),
        migrations.RemoveField(
            model_name='travelclassseatcapacity',
            name='travel_class',
        ),
        migrations.RemoveField(
            model_name='travelclassseatcapacity',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='airplane',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='travel_class',
        ),
        migrations.AddField(
            model_name='flight',
            name='airline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airline.Airline'),
        ),
        migrations.DeleteModel(
            name='Airplane',
        ),
        migrations.DeleteModel(
            name='TravelClass',
        ),
        migrations.DeleteModel(
            name='TravelClassSeatCapacity',
        ),
    ]
