# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-02 20:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('airline', '0006_auto_20160501_2229'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='price',
            field=models.CharField(default='KES0', max_length=50),
        ),
        migrations.AlterField(
            model_name='trip',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_destination', to='airline.CityLookup'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='origin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_origin', to='airline.CityLookup'),
        ),
    ]
